### PR TITLE
Add missing deps

### PR DESCRIPTION
**Pull request by JakeChampion**
I tried running `make` and was met with some missing deps. I've added them as dev dependencies.

### CODE REVIEW

**Comment by WebReflection** [comment]
travis not happy ... have you tried running `make dependencies` instead?

**Comment by JakeChampion** [comment]
I've never seen a project approach dependency installation like this before. Why did you make a `make dependencies` command instead of adding the modules to package.json?

**Comment by WebReflection** [comment]
habit from https://github.com/WebReflection/gitstrap#gitstrap

did you managed to build?

**Comment by WebReflection** [comment]
( to give you more context, not everything I do is handled by npm and is in the npm registry, at least not most of my old projects, hence the usage of make )

**Comment by JakeChampion** [comment]
I managed to build via `make dependencies` :+1:

**Pull request closed without merging**
